[terminal]
# Keep 7, since agetty is started 1-6
vt = 7

[default_session]
command = "tuigreet --cmd 'dbus-run-session niri --session' --window-padding 1 --time --time-format '%R - %F' --remember --remember-session --asterisks --power-shutdown 'loginctl poweroff' --power-reboot 'loginctl reboot' --power-no-setsid"
user = "_greeter"
