promptToReturnFromSubprocess: false

gui:
  scrollHeight: 1
  expandFocusedSidePanel: true
  language: en
  timeFormat: 2015/02/25
  shortTimeFormat: 15:04
  nerdFontsVersion: 3
  showDivergenceFromBaseBranch: arrowAndNumber
  filterMode: fuzzy

git:
  autoFetch: false
  autoRefresh: false
  autoForwardBranches: none

os:
  editPreset: helix (hx)
  open: xdg-open '{{filename}}'
  openLink: xdg-open '{{link}}'
  copyToClipboardCmd: echo -n '{{text}}' | wl-copy
  readFromClipboardCmd: wl-paste

update:
  method: never
