theme = "gruvbox"

[editor]
auto-completion = false
auto-format = false
auto-info = false
clipboard-provider = "wayland"
color-modes = true
continue-comments = false
line-number = "relative"
middle-click-paste = false
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
git-global = false
ignore = false
parents = false

[editor.lsp]
goto-reference-include-declaration = false

[keys.normal]
"C-," = "decrement"
"C-." = "increment"
C-a = "no_op"
C-p = "save_selection"
C-q = ":quit-all"
C-s = ":write!"
C-x = ":write-quit-all"
[keys.normal.space.l]
c = ":lsp-workspace-command"
r = ":lsp-restart"
s = ":lsp-stop"

[keys.select]
C-p = "save_selection"
C-q = ":quit-all"
C-s = ":write!"
C-x = ":write-quit-all"

[keys.insert]
A-b = ["move_prev_word_start", "collapse_selection"]
A-f = ["move_next_word_end", "move_char_right"]
C-a = "goto_line_start"
C-b = "move_char_left"
C-backspace = "delete_word_backward"
C-e = "goto_line_end"
C-f = "move_char_right"
C-n = "move_visual_line_down"
C-p = "move_visual_line_up"
C-q = ":quit-all"
C-s = ":write!"
C-space = "completion"
C-x = ":write-quit-all"
